version: '3.8'

services:
  # Base de datos para WordPress
  mysql_wp:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - mysql_wp_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # Base de datos para el proyecto PHP
  mysql_php:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwes
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
    volumes:
      - mysql_php_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # phpMyAdmin para administrar ambas bases de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql_wp,mysql_php

  # WordPress
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_wp:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

  # Servidor Apache con PHP para el proyecto
  apache:
    build: ./apache
    restart: always
    ports:
      - "8081:80"
    volumes:
      - php_project:/var/www/html

  # PHP-FPM para el proyecto PHP
  php:
    build: ./php
    restart: always
    volumes:
      - php_project:/var/www/html
    depends_on:
      - mysql_php

volumes:
  mysql_wp_data:
  mysql_php_data:
  wordpress_data:
  php_project:
